version: "3"
services:

  redisdb:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  sqldb:
    image: dbafromthecold/sqlserver2012express
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

  esdb:
    image: elasticsearch:7.12.1
    ports:
      - 9200
      - 9300
    networks:
      - backend    
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

  authserver:
    image: zcfx/abp-mic-authserver:v3
    ports:
      - 5001:80
    networks:
      - backend
    depends_on:
      - redisdb
      - sqldb
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  

networks:  
  backend:


